name: tiffintales
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  http: ^1.3.0
  material_color_utilities: ^0.11.1  # Updated to match the version used by flutter_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add the assets section for your images and fonts
  assets:
    - assets/logo.png
    - assets/google-icon.png
    - assets/apple-icon.png

  # Specify the custom font (Kufam Semibold)
  fonts:
    - family: Kufam
      fonts:
        - asset: assets/fonts/Kufam-SemiBold.ttf
          weight: 600 # This is for the semibold weight
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500